//AddSong("Artist Name","Song Name","Genre Name","File lovation in terms of songs/","Image location","Album Name")
//    "Album Name" should be the same file in img/albums/ to display the image


AddSong("Adam Lambert","Ghost Town","o","AdamLambertGhostTown.mp3","img/artists/aerochord.png","No Album")
AddSong("Adele","Hello","o","AdeleHello.mp3","img/artists/aerochord.png","No Album")
AddSong("Alan Walker","Sing Me To Sleep","o","AlanWalkerSingMeToSleep.mp3","img/artists/aerochord.png","No Album")
AddSong("Archie V","Ghost Town","o","ArchieVFritz.mp3","img/artists/aerochord.png","No Album")
AddSong("Archie V","Nobody Likes Me","o","ArchieVNobodyLikesMe.mp3","img/artists/aerochord.png","No Album")
AddSong("Archie V","SuperToast","o","ArchieVSuperToast","img/artists/aerochord.png","No Album")
AddSong("Arianda Grande","Focus","o","AriandaGrandeFocus.mp3","img/artists/aerochord.png","No Album")
AddSong("Awolnation","Sail","o","AwolnationSail.mp3","img/artists/aerochord.png","No Album")
AddSong("Backstreet Boys","Everybody","o","BackstreetBoysEverybody.mp3","img/artists/aerochord.png","No Album")
AddSong("Birdy","Not About Angels","o","BirdyNotAboutAngels.mp3","img/artists/aerochord.png","No Album")
AddSong("Blasterjaxx","Faith","o","BlasterjaxxFaith.mp3","img/artists/aerochord.png","No Album")
AddSong("Cheryl","I Don't Care","o","Cheryl_IDontCare.mp3","img/artists/aerochord.png","No Album")
AddSong("Darude","Sandstorm [MLG Trap Remix]","Trap","DarudeSandstormMLGTrapRemix.mp3","img/artists/aerochord.png","No Album")
AddSong("Dawin","Dessert","o","DawinDessert.mp3","img/artists/aerochord.png","No Album")
AddSong("Dimitri Vegas","Higher Place","o","DimitriVegasHigherPlace.mp3","img/artists/aerochord.png","No Album")
AddSong("DJ Khaled","For Free","o","DJKhaledForFree.mp3","img/artists/aerochord.png","No Album")
AddSong("DJ Snake","Get Low","o","DJSnakeGetLow.mp3","img/artists/aerochord.png","No Album")
AddSong("DJ Snake","Middle","o","DJSnakeMiddle.mp3","img/artists/aerochord.png","No Album")
AddSong("DVBBS","TSUNAMI","o","DVBBSTSUNAMI.mp3","img/artists/aerochord.png","No Album")
AddSong("Ellie Goulding","On My Mind","o","EllieGouldingOnMyMind.mp3","img/artists/aerochord.png","No Album")
AddSong("ETC!ETC!","Swoop","o","ETCETCSwoop.mp3","img/artists/aerochord.png","No Album")
AddSong("Fall Out Boy","Centuries","o","FallOutBoyCenturies.mp3","img/artists/aerochord.png","No Album")
AddSong("Fall Out Boy","Uma Thurman","o","FallOutBoyUmaThurman.mp3","img/artists/aerochord.png","No Album")
AddSong("Flux Pavilion","I Can't Stop","o","FluxPavilionICantStop.mp3","img/artists/aerochord.png","No Album")
AddSong("Grace","You Don't Own Me","o","GraceYouDontOwnMe.mp3","img/artists/aerochord.png","No Album")
AddSong("Haddaway","What Is Love","o","HaddawayWhatIsLove.mp3","img/artists/aerochord.png","No Album")
AddSong("iHeartMemphis","Hit The Quan","o","iHeartMemphisHitTheQuan.mp3","img/artists/aerochord.png","No Album")
AddSong("John Legend","All Of Me [Tiesto Remix]","o","JohnLegendAllOfMeTiesto.mp3","img/artists/aerochord.png","No Album")
AddSong("Justin Bieber","I Will Show You","o","JustinBieberIWillShowYou.mp3","img/artists/aerochord.png","No Album")
AddSong("Justin Bieber","Sorry","o","JustinBieberSorry.mp3","img/artists/aerochord.png","No Album")
AddSong("Kaskade","Disarm You [Illenium Remix]","o","KaskadeDisarmYouIlleniumRemix.mp3","img/artists/aerochord.png","No Album")
AddSong("Kehlani","Gangsta","o","KehlaniGangsta.mp3","img/artists/aerochord.png","No Album")
AddSong("Kendrick Lamar","Swimming Pools","o","KendrickLamarSwimmingPools.mp3","img/artists/aerochord.png","No Album")
AddSong("Kevin Gates","2 Phones","o","KevinGates2Phones.mp3","img/artists/aerochord.png","No Album")
AddSong("Men Without Hats","Safety Dance","o","MenWithoutHatsSafetyDance.mp3","img/artists/aerochord.png","No Album")
AddSong("OMI","Cheerleader","o","OMICheerleader.mp3","img/artists/aerochord.png","No Album")
AddSong("OMI","Cheerleader [Remix]","o","OMICheerLeaderRemix.mp3","img/artists/aerochord.png","No Album")
AddSong("Parasyte","Romanesque","o","ParasyteRomanesque.mp3","img/artists/aerochord.png","No Album")
AddSong("Pegboard Nerds","Here It Comes","o","PegboardNerdsHereItComes.mp3","img/artists/aerochord.png","No Album")
AddSong("ProjectX","Heads Will Roll [A-Trak Remix]","o","ProjectXHeadsWillRollATrakRemix.mp3","img/artists/aerochord.png","No Album")
AddSong("RCity","LockedAway","o","RCityLockedAway.mp3","img/artists/aerochord.png","No Album")
AddSong("Rixton","Me And My Broken Heart","o","RixtonMeAndMyBrokenHeart.mp3","img/artists/aerochord.png","No Album")
AddSong("Robin Thicke","Blurred Lines","o","RobinThickeBlurredLines.mp3","img/artists/aerochord.png","No Album")
AddSong("Shawn Mendes","Treat You Better","o","ShawnMendesTreatYouBetter.mp3","img/artists/aerochord.png","No Album")
AddSong("Stephen","Bullet Train","o","StephenBulletTrain.mp3","img/artists/aerochord.png","No Album")
AddSong("Steve Aoki","Home We'll Go","o","SteveAokiHomeWeWillGo.mp3","img/artists/aerochord.png","No Album")
AddSong("The Chainsmokers","Don't Let Me Down","o","TheChainsmokersDontLetMeDown.mp3","img/artists/aerochord.png","No Album")
AddSong("The Chainsmokers","Closer","o","TheChainsmokersCloser.mp3","img/artists/aerochord.png","No Album")
AddSong("The Weeknd","Low Life","o","TheWeekndLowLife.mp3","img/artists/aerochord.png","No Album")
AddSong("The Weeknd","The Hills","o","TheWeekndTheHills.mp3","img/artists/aerochord.png","No Album")
AddSong("DJ Snake","Turn Down For What","o","TurnDownForWhat.mp3","img/artists/aerochord.png","No Album")
AddSong("Voxxin","Rule 34","o","VoxxinRule34.mp3","img/artists/aerochord.png","No Album")
AddSong("Wiz Khalifa","See You Again","o","WizKhalifaSeeYouAgain.mp3","img/artists/aerochord.png","No Album")
AddSong("Yellow Claw","DJ Turn It Up","o","YellowClawDJTurnItUp.mp3","img/artists/aerochord.png","No Album")
AddSong("Yellow Claw","IBETCHU","o","YellowClawIBETCHU.mp3","img/artists/aerochord.png","No Album")
AddSong("Yellow Claw","Legends","o","YellowClawLegends.mp3","img/artists/aerochord.png","No Album")
AddSong("Yellow Claw","Psycho","o","YellowClawPsycho.mp3","img/artists/aerochord.png","No Album")
AddSong("Yellow Claw","Till It Hurts","o","YellowClawTillItHurts.mp3","img/artists/aerochord.png","No Album")
